### ISSUE TITLE
properly sign our packages with our own gpg signature

### ISSUE THREAD

**Issue by efiop** [iterative/dvc-s3-repo#3]
Currently we auto-generate a one-off signature each time we deploy a release, which isn't nice and will result in users getting warnings.

https://github.com/iterative/dvc/issues/4193
https://discordapp.com/channels/485586884165107732/485596304961962003/732947583520997456

**Comment by casperdcl** [comment]
is it an option to have a master gpg key which we use to sign the generated ones?

**Comment by casperdcl** [comment]
Otherwise can just `gpg -a --export-secret-keys <KEY>` into a CI env var and `gpg --import` in the CI. I use that approach in a few packages.

**Comment by kenahoo** [comment]
For users experiencing this warning, what's a good course of action?  It's not actually clear to me whether everything is working correctly but noisily, or things aren't working correctly:

```
% sudo apt-get update
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Hit:2 http://archive.ubuntu.com/ubuntu bionic InRelease                                                        
Get:3 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [1543 kB]    
Get:4 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]                              
Get:6 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1108 kB]                           
Get:7 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]               
Get:8 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [1883 kB]                                                
Get:5 https://s3-us-east-2.amazonaws.com/dvc-s3-repo/deb stable InRelease [2679 B]                                                 
Ign:5 https://s3-us-east-2.amazonaws.com/dvc-s3-repo/deb stable InRelease                 
Get:9 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1717 kB]
Fetched 6506 kB in 6s (1134 kB/s)                      
Reading package lists... Done
W: GPG error: https://s3-us-east-2.amazonaws.com/dvc-s3-repo/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 413F80646046B803

% echo $?
0
```

**Comment by efiop** [comment]
@kenahoo Oops, sorry for the late reply. It is just a warning, everything should be working correctly in other aspects.

**Comment by efiop** [comment]
Ok, we now have both deb and rpm signed with our key. Instructions on importing a private key are updated in README and in docs. Thanks again for the feedback and tips! :pray:
