### ISSUE TITLE
rpm builds failing

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc-s3-repo#86]
`rpm` builds are failing, as it is not able to install `pygit2` from wheel, and instead tries to build from source.

I believe this is due to pygit2 providing `manylinux_2_24` wheels. An easier temporary solution might be to pin `pygit2==1.10.1`. A proper solution might be to update centos or use fedora?

**Comment by skshetry** [comment]
I don't have a good understanding of how rpm builds work.

**Comment by efiop** [comment]
Thanks for the research @skshetry ! 🙏
