### ISSUE TITLE
fedora 35 and rpm-s3 break CI

### ISSUE THREAD

**Issue by dtrifiro** [iterative/dvc-s3-repo#94]
Recent updates to fedora 35 (related: https://github.com/iterative/dvc-s3-repo/pull/88, https://github.com/iterative/dvc-s3-repo/pull/93) break CI for the RPM package: https://github.com/efiop/rpm-s3 is a python2 package, and fedora 35 installs 3 by default.

**Comment by efiop** [comment]
i guess we've used old distro in that rpm building step for a reason. Since we only need newer fedora only for testing, probably need to revert and run test script without that docker file.
